package com.yw.domain;
// Generated Dec 1, 2016 10:49:24 AM by Hibernate Tools 3.4.0.CR1

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private String id;
	private String list;

	public Cart() {
	}

	public Cart(String id, String list) {
		this.id = id;
		this.list = list;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getList() {
		return this.list;
	}

	public void setList(String list) {
		this.list = list;
	}

}
