package com.yw.domain;
// Generated Nov 23, 2016 1:01:31 PM by Hibernate Tools 3.4.0.CR1

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private String id;
	private String name;
	private boolean isFolder;

	public Category() {
	}
	
	public Category(String id) {
		this.id = id;
	}

	public Category(String id, String name, boolean isFolder) {
		this.id = id;
		this.name = name;
		this.isFolder = isFolder;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isIsFolder() {
		return this.isFolder;
	}

	public void setIsFolder(boolean isFolder) {
		this.isFolder = isFolder;
	}

}
