package com.yw.domain;
// Generated Nov 29, 2016 3:45:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Knowledge generated by hbm2java
 */
public class Knowledge implements java.io.Serializable {

	private String id;
	private String name;
	private boolean isFolder;

	public Knowledge() {
	}
	
	public Knowledge(String id) {
		this.id = id;
	}

	public Knowledge(String id, String name, boolean isFolder) {
		this.id = id;
		this.name = name;
		this.isFolder = isFolder;
		
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isIsFolder() {
		return this.isFolder;
	}

	public void setIsFolder(boolean isFolder) {
		this.isFolder = isFolder;
	}


}
