package com.yw.domain;
// Generated Nov 29, 2016 3:45:16 PM by Hibernate Tools 3.4.0.CR1

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private Integer id;
	private Knowledge knowledge;
	private int type;
	private String memo;
	private String answer;
	private String source;
	private String year;


	public Question() {
	}

	public Question(Integer id) {
		this.id = id;
	}
	public Question(Knowledge knowledge, int type, String year) {
		this.knowledge = knowledge;
		this.type = type;
		this.year = year;
		
	}

	public Question(Knowledge knowledge, int type, String memo, String answer, String source, String year) {
		this.knowledge = knowledge;
		this.type = type;
		this.memo = memo;
		this.answer = answer;
		this.source = source;
		this.year = year;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Knowledge getKnowledge() {
		return this.knowledge;
	}

	public void setKnowledge(Knowledge knowledge) {
		this.knowledge = knowledge;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
