package com.yw.domain;
// Generated Nov 23, 2016 1:01:31 PM by Hibernate Tools 3.4.0.CR1

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private Integer id;
	private int type;
	private String memo;
	private String answer;
	private String source;
	private String year;
	private String category;
	private String oid;

	public Question() {
	}

	public Question(int id) {
		this.id = id;
	}
	
	public Question(int type, String year, String category, String oid) {
		this.type = type;
		this.year = year;
		this.category = category;
		this.oid = oid;
	}

	public Question(int type, String memo, String answer, String source, String year, String category, String oid) {
		this.type = type;
		this.memo = memo;
		this.answer = answer;
		this.source = source;
		this.year = year;
		this.category = category;
		this.oid = oid;
	}
	
	public Question(int type, String memo, String answer, String source, String year, String category) {
		this.type = type;
		this.memo = memo;
		this.answer = answer;
		this.source = source;
		this.year = year;
		this.category = category;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

}
